apiVersion: neotoma v2.0
headers: 2.0
kind: Development
metadata:
- column: depth_mid_cm
  neotoma: ndb.analysisunits.depth
  rowwise: true
  type: float
- column: thick_cm
  neotoma: ndb.analysisunits.thickness
  rowwise: true
  type: float
- column: age_mid_cal_yr_bp
  neotoma: ndb.sampleages.age
  rowwise: yes
  type: float
  chronologyname: Default Fire Proxy Database Chronology
- column: samplenotes_full
  neotoma: ndb.samples.notes
  type: string
  rowwise: true
- column: controlled_element
  neotoma: ndb.variables.variableelementid
  rowwise: yes
  type: string
  taxonname: Charcoal
- column: controlled_units
  neotoma: ndb.variables.variableunitsid
  rowwise: yes
  taxonname: Charcoal
  type: string
- column: value
  neotoma: ndb.data.value
  rowwise: yes
  type: float
  taxonname: Charcoal
- column: sample_quantity_value
  neotoma: ndb.data.value
  rowwise: yes
  type: float
  taxonname: Sample Quantity
- column: sample_quantity_ELEMENT
  neotoma: ndb.variables.variableelementid
  rowwise: yes
  type: string
  taxonname: Sample Quantity
- column: sample_quantity_UNITS
  neotoma: ndb.variables.variableunitsid
  rowwise: yes
  type: string
  taxonname: Sample Quantity
- column: entity_name
  neotoma: ndb.sites.sitename
  type: string
- column: entity_name
  neotoma: ndb.collectionunits.handle
  type: string
- column: lat_dd_north
  neotoma: ndb.sites.geog.latitude
  type: float
- column: lon_dd_east
  neotoma: ndb.sites.geog.longitude
  type: float
- column: elev_m
  neotoma: ndb.sites.altitude
  type: int
- column: country_entity
  neotoma: ndb.geopoliticalunits.politicalunit1
  type: string
- column: location_desc
  neotoma: ndb.sites.sitedescription
  type: string
- column: controlled_dep
  neotoma: ndb.collectionunits.depenvtid
  type: string
- column: year
  neotoma: ndb.publications.year
  type: string
- column: citation
  neotoma: ndb.publications.citation
  type: string
- column: articletitle
  neotoma: ndb.publications.articletitle
  type: string
- column: journal
  neotoma: ndb.publications.journal
  type: string
- column: doi
  neotoma: ndb.publications.doi
  type: string
- column: datasetname
  neotoma: ndb.datasets.datasetname
  type: string
- column: datasettype
  neotoma: ndb.datasets.datasettypeid
  type: string
- column: datasetnotes_full
  neotoma: ndb.datasets.notes
  type: string
- column: contactname
  neotoma: ndb.contacts.contactname
  type: string
- column: familyname
  neotoma: ndb.contacts.familyname
- column: givennames
  neotoma: ndb.contacts.givennames
  type: string
- column: email
  neotoma: ndb.contacts.email
  type: string
- column: depth_cm_geo
  neotoma: ndb.geochronology.depth
  rowwise: true
  type: float
- column: thick_cm_geo
  neotoma: ndb.geochronology.thickness
  rowwise: yes
  type: float
- column: neotoma_geochrontype
  neotoma: ndb.geochronology.geochrontypeid
  rowwise: yes
  type: string
- column: neotoma_chroncontroltypes
  neotoma: ndb.chroncontrols.chroncontroltypeid
  rowwise: yes
  type: string
- column: material
  neotoma: ndb.geochronology.materialdated
  rowwise: yes
  type: string
- column: error
  neotoma: ndb.geochronology.erroryounger
  rowwise: yes
  type: float
- column: error
  neotoma: ndb.geochronology.errorolder
  rowwise: yes
  type: float
- column: lab_number
  neotoma: ndb.geochronology.labnumber
  rowwise: yes
  type: string
- column: notes_geo
  neotoma: ndb.geochronology.notes
  rowwise: yes
  type: string
- column: age_geo
  neotoma: ndb.geochronology.age
  rowwise: yes
  type: float
- column: chroncontrol_limityounger
  neotoma: ndb.chroncontrols.agelimityounger
  rowwise: yes
  type: float
- column: chroncontrol_limitolder
  neotoma: ndb.chroncontrols.agelimitolder
  rowwise: yes
  type: float
- column: chroncontrol_depth
  neotoma: ndb.chroncontrols.depth
  rowwise: yes
  type: float
- column: chroncontrol_age
  neotoma: ndb.chroncontrols.age
  rowwise: yes
  type: float
- column: chroncontrol_thickness
  neotoma: ndb.chroncontrols.thickness
  type: float
  rowwise: yes
- column: chroncontrol_comments
  neotoma: ndb.chroncontrols.notes
  rowwise: yes
  type: string
- column: chronology_notes_full
  neotoma: ndb.chronologies.notes
  type: string
  chronologyname: Default Fire Proxy Database Chronology
- column: ageboundolder
  neotoma: ndb.chronologies.ageboundolder
  type: float
  chronologyname: Default Fire Proxy Database Chronology
- column: ageboundyounger
  neotoma: ndb.chronologies.ageboundyounger
  type: float
  chronologyname: Default Fire Proxy Database Chronology
- column: agetype
  neotoma: ndb.chronologies.agetypeid
  type: string
  chronologyname: Default Fire Proxy Database Chronology
- column: agetype
  neotoma: ndb.chroncontrols.agetypeid
  rowwise: yes
  type: string
- column: agetype
  neotoma: ndb.geochronology.agetypeid
  rowwise: yes
  type: string
#- column: depth_cm_geo
#  neotoma: ndb.analysisunits.depth
#  notes:
#  required:
#  rowwise: true
#  type: float
#- column: thick_cm_geo
#  neotoma: ndb.analysisunits.thickness
#  notes:
#  required:
#  rowwise: true
#  type: float
- column: databaseid
  neotoma: 'ndb.datasetdatabases.databasename'
  required: true
  value: Global Paleofire Database
- column: date_id
  neotoma: _link_chroncontrol
  link_id: chroncontrol
  required: true
  rowwise: true
  type: int